# =============================================================================
# NHÓM 2: Backend Độc lập - productcatalogservice
# =============================================================================
apiVersion: apps/v1
kind: Deployment
metadata:
  name: productcatalogservice-online-boutique
  namespace: {{ include "online-boutique.namespace" . }}
  labels:
    app: productcatalogservice-online-boutique
    group: "2-backend-independent"
spec:
  selector:
    matchLabels:
      app: productcatalogservice-online-boutique
  template:
    metadata:
      labels:
        app: productcatalogservice-online-boutique
    spec:
      serviceAccountName: productcatalogservice-online-boutique
      terminationGracePeriodSeconds: 5
      securityContext:
        fsGroup: 1000
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
      imagePullSecrets:
        {{- range .Values.imagePullSecrets }}
        - name: {{ .name }}
        {{- end }}
      containers:
      - name: server
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
          privileged: false
          readOnlyRootFilesystem: true
        image: "{{ .Values.productcatalogservice.image.repository }}:{{ .Values.productcatalogservice.image.tag }}"
        imagePullPolicy: {{ .Values.productcatalogservice.image.pullPolicy }}
        ports:
        - containerPort: 3550
        env:
        - name: PORT
          value: "3550"
        - name: DISABLE_PROFILER
          value: "1"
        readinessProbe:
          grpc:
            port: 3550
        livenessProbe:
          grpc:
            port: 3550
        resources:
          requests:
            cpu: {{ .Values.productcatalogservice.resources.requests.cpu }}
            memory: {{ .Values.productcatalogservice.resources.requests.memory }}
          limits:
            cpu: {{ .Values.productcatalogservice.resources.limits.cpu }}
            memory: {{ .Values.productcatalogservice.resources.limits.memory }}
---
apiVersion: v1
kind: Service
metadata:
  name: productcatalogservice-online-boutique
  namespace: {{ include "online-boutique.namespace" . }}
  labels:
    app: productcatalogservice-online-boutique
spec:
  type: ClusterIP
  selector:
    app: productcatalogservice-online-boutique
  ports:
  - name: grpc
    port: 3550
    targetPort: 3550
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: productcatalogservice-online-boutique
  namespace: {{ include "online-boutique.namespace" . }}
